name: Docker Build and Deploy

on:
  push:
    branches:
      - ubuntu-monitor

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Bash syntax
        run: shellcheck ./ubuntu-monitor/sys_stat.sh

      - name: Build Docker image
        run: docker build -t ubuntu-monitor ./ubuntu-monitor

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # --- ВОТ ЭТОТ БЛОК МЫ ВСТАВИЛИ ---
      - name: Check if secret is empty
        env:
          MY_KEY: ${{ secrets.SSH_KEY }}
        run: |
          if [ -z "$MY_KEY" ]; then
            echo "ERROR: SSH_KEY is empty or not found!"
            exit 1
          else
            echo "SSH_KEY is present. Character count: ${#MY_KEY}"
          fi
      # --- КОНЕЦ БЛОКА ПРОВЕРКИ ---

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Denys
            git pull origin ubuntu-monitor
            docker compose up -d --build
